chat/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('chat/<str:username>/', views.chat, name='chat'),
]

chatadvanced/urls.py
from django.urls import path
from .views import DashboardView, UserListView, ChatView


app_name = 'chatadvanced'
urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('user-list/', UserListView.as_view(), name='user_list'),
    path('user-list/<str:username>/', ChatView.as_view(), name='chat'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('', include("chat.urls")),
    path('chat-advanced/', include("chatadvanced.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save


class ChatGroup(models.Model):
    name = models.CharField(max_length=250)
    users = models.ManyToManyField(User)

    def __str__(self):
        return self.name


class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    chatgroup = models.ForeignKey(ChatGroup, on_delete=models.CASCADE)
    body = models.CharField(max_length=500)
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.body


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    status = models.CharField(max_length=150, default='offline')
    image = models.ImageField(upload_to='images/profile/', default='profile.jpg')

    def __str__(self):
        return str(self.user.username)


@receiver(sender=User, signal=post_save)
def create_profile(sender, instance, created, *args, **kwargs):
    if created:
        Profile.objects.create(user=instance)

chatadvanced/models.py
from django.db import models

# Create your models here.

chat/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from .models import ChatGroup
from django.contrib.auth.decorators import login_required


@login_required
def index(request):
    return render(request, 'index.html')


@login_required
def chat(request, username):
    users = User.objects.exclude(id=request.user.id)
    user1 = User.objects.get(username=request.user.username)
    user2 = User.objects.get(username=username)

    chat_group = ChatGroup.objects.filter(users=user1).filter(users=user2).first()

    if not chat_group:
        chat_group = ChatGroup.objects.create(
            name=f"chat_between_{user1.username}_and_{user2.username}"
        )
        chat_group.users.add(user1, user2)

    context = {
        'users': users,
        'user1': user1,
        'user2': user2,
        'chatgroup': chat_group
    }
    return render(request, 'chat.html', context)

chatadvanced/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin


class DashboardView(LoginRequiredMixin, ListView):
    def get(self, request, *args, **kwargs):
        return render(request, 'base1.html')


class UserListView(LoginRequiredMixin, ListView):
    def get(self, request, *args):
        return render(request, 'user-list.html')


class ChatView(LoginRequiredMixin, ListView):
    def get(self, request, **kwargs):
        username = kwargs['username']
        return render(request, 'chat1.html')

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" >
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}

        {% endblock %}
    </title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css'>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- partial:index.partial.html -->
<div class="container clearfix">
    <div class="people-list" id="people-list">
        <div class="search">
            <input type="text" placeholder="search" />
            <i class="fa fa-search"></i>
        </div>

        <form method="post" action="{% url 'logout' %}">
            {% csrf_token %}
            <button type="submit">Logout</button>
        </form>


        <ul class="list" id="userList">
            {% for user in users %}

                <li class="clearfix">
                    <img src="{{ user.profile.image.url }}" alt="avatar" />
                    <div class="about">
                        <a class="name" href="{% url 'chat' user.username %}">
                            {{ user.get_full_name }}
                        </a>
                        <div class="status">
                          <i class="fa fa-circle {% if user.profile.status == 'online' %} online {% else %} offline {% endif %}"></i>
                            {{ user.profile.status }}
                        </div>
                    </div>
                </li>
            {% endfor %}
      </ul>
    </div>

    {% block content %}

    {% endblock %} <!-- end chat -->

  </div> <!-- end container -->

<script>
        const authUser = '{{ request.user.username }}'
        const userSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/users/'
        );

        userSocket.onmessage = function(e) {
            const datas = JSON.parse(e.data);
            const userList = document.getElementById('userList');
            userList.innerHTML = ""
            for(i = 0; i < datas.length; i++) {
                var data = datas[i];
                var userListHtml = '<li class="clearfix">\
                        <img src="' + data.picture + '" alt="avatar" />\
                        <div class="about">\
                            <a class="name" href="/chat/' + data.username + '/">' +
                                data.full_name
                            + '</a>\
                            <div class="status">\
                              <i class="fa fa-circle ' + data.status + '"></i>' +
                                data.status
                            + '</div>\
                        </div>\
                    </li>'
                if (data.username != authUser)
                    userList.innerHTML += userListHtml
            }
        };

        userSocket.onclose = function(e) {
            console.error('Chat socket error(user list)');
        };
    </script>

<!-- partial -->
  <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.0/handlebars.min.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/list.js/1.1.1/list.min.js'></script>
<script  src="{% static 'script.js' %}"></script>

</body>
</html>

templates/base1.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chat Page</title>
    <link rel="stylesheet" href="{% static 'style-chat.css' %}">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" />

</head>

<body>
    <section>
        <div class="left">
            <div class="iconBx">
                <div class="user">
                    <img src="{% static 'images/admin.jpg' %}" alt="admin">
                </div>
                <div class="icon">
                    <a href="#">
                        <i class="far fa-home-lg-alt"></i>
                        <span>home</span>
                    </a>
                    <a href="#" class="active">
                        <i class="fal fa-comment-dots"></i>
                        <span>message</span>
                    </a>
                    <a href="#">
                        <i class="fal fa-bell"></i>
                        <span>alert</span>
                    </a>
                    <a href="#">
                        <i class="fal fa-cog"></i>
                        <span>settings</span>
                    </a>
                </div>
            </div>
            <div class="logOut">
                <a href="#">
                    <i class="fal fa-sign-out-alt"></i>
                    <span>logout</span>
                </a>
            </div>
        </div>

        {% block content %}

        {% endblock %}

    </section>
</body>

</html>

templates/chat.html
{% extends 'base.html' %}

{% block title %}
	{{ title }} - chat
{% endblock %}

{% block content %}
	<div class="chat">
        <div class="chat-header clearfix">
            <img src="{{ user2.profile.image.url }}" alt="avatar" width="50px" style="border-radius: 50%"/>

            <div class="chat-about">
                <div class="chat-with">
                    {{ user2.get_full_name }}
                </div>
                <div class="chat-num-messages">{{ user2.profile.status }}</div>
            </div>
            <i class="fa fa-star"></i>
        </div> <!-- end chat-header -->

        <div class="chat-history">
            <ul id="chat-messages">

            </ul>

        </div> <!-- end chat-history -->

        <div class="chat-message clearfix">
            <input name="message-to-send" id="chat-message-input" placeholder ="Type your message" style="width: 100%; height: 50px; padding: 5px; margin-bottom: 20px;">

            <i class="fa fa-file-o"></i> &nbsp;&nbsp;&nbsp;
            <i class="fa fa-file-image-o"></i>

        <button id="chat-message-submit">Send</button>

      </div> <!-- end chat-message -->

    </div>

    {{ room_name|json_script:"room-name" }}
    <script>
        const roomName = '{{ chatgroup.name }}'
        const user_id = '{{ request.user.id }}'
        const chatMessages = document.getElementById('chat-messages')
        const chat_history = document.querySelector('.chat-history')

        function scroll_bottom(){
            chat_history.scrollTop = chat_history.scrollHeight;
        }

        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/chat/'
            + roomName
            + '/'
        );

        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            const myMessageHtml = '<li class="clearfix">\
                                        <div class="message-data align-right">\
                                            <span class="message-data-time" >' + data.time + '</span> &nbsp; &nbsp;\
                                            <span class="message-data-name" > {{ user1.first_name }} </span>\
                                        </div>\
                                        <div class="message other-message float-right">' +
                                            data.message + '</div></li>'
            const chatMessageHtml = '<li>\
                                        <div class="message-data">\
                                            <span class="message-data-time" >' + data.time + '</span> &nbsp; &nbsp;\
                                            <span class="message-data-name" > {{ user2.first_name }} </span>\
                                        </div>\
                                        <div class="message my-message">' +
                                            data.message + '</div></li>'

            if(data.sender_id == user_id){
                messageHtml = myMessageHtml
            }else{
                messageHtml = chatMessageHtml
            }
            chatMessages.innerHTML += messageHtml;
            scroll_bottom()
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly', e);
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.key === 'Enter') {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message,
                'sender_id': user_id,
            }));
            messageInputDom.value = '';
        };
        scroll_bottom()
    </script>

{% endblock %}

templates/chat1.html
{% extends 'user-list.html' %}
{% load static %}

{% block title %}
	{{ title }}
{% endblock %}


{% block chat %}
        <header>
            <div class="imgBx">
                <img src="{% static 'images/antMan.jpg' %}" alt="antMan">
            </div>
            <div class="title">
                <h2>Ant Man</h2>
                <p>online - last seen 10:53pm</p>
            </div>
            <div class="headIconBx">
                <a href="#">
                    <i class="far fa-phone-alt"></i>
                </a>
                <a href="#">
                    <i class="far fa-video"></i>
                </a>
                <a href="{% url 'chatadvanced:user_list' %}">
                    <i class="far fa-window-close"></i>
                </a>
            </div>
        </header>
        <div class="chatBx">
            <div class="messages leftSide">
                <h2>Hey there!</h2>
                <p>today,08:30pm</p>
            </div>
            <div class="messages leftSide">
                <h2>How are you?</h2>
                <p>today,08:31pm</p>
            </div>
            <div class="messages rightSide">
                <h2>Hello!</h2>
                <p>today,09:01pm</p>
            </div>
            <div class="messages rightSide">
                <h2>I am fine and how about you?</h2>
                <p>today,09:02pm</p>
            </div>
            <div class="messages leftSide">
                <h2>I am doing well. Can we meet tomorrow?</h2>
                <p>today,09:22pm</p>
            </div>
            <div class="messages rightSide">
                <h2>Yes, Sure!</h2>
                <p>today,09:42pm</p>
            </div>
            <div class="messages leftSide">
                <h2>Okk, bye</h2>
                <p>today,09:44pm</p>
            </div>
            <div class="messages rightSide">
                <h2>Okk, good luck!</h2>
                <p>today,09:45pm</p>
            </div>
            <div class="messages leftSide">
                <h2><img src="{% static 'images/chat.jpg' %}" alt="chat"></h2>
            </div>
            <div class="messages leftSide">
                <h2>Good luck! Captain.</h2>
                <p>today,09:45pm</p>
            </div>
        </div>
        <div class="inputBx">
            <div class="input">
                <div class="search">
                    <i class="far fa-paperclip"></i>
                    <input type="text" placeholder="Type your message here...">
                </div>
                <div class="inputIcon">
                    <i class="fal fa-grin-alt"></i>
                    <i class="fal fa-camera"></i>
                </div>
            </div>
            <div class="mic">
                <i class="fas fa-microphone"></i>
            </div>
        </div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block title %}
	Django channels advanced
{% endblock %}

{% block content %}
    <div class="chat" style="height: 855px">

    </div>
{% endblock %}

templates/user-list.html
{% extends 'base1.html' %}
{% load static %}

{% block title %}
	{{ title }}
{% endblock %}


{% block content %}
	<main>
        <div class="searchBx">
            <i class="fal fa-search"></i>
            <input type="text" placeholder="Search">
        </div>
        <div class="box person">
            <div class="title">
                <h2>person</h2>
            </div>
            {% for user in users %}
            	<a href="{% url 'chatadvanced:chat' user.username %}">
                    <img src="{% static 'user.' %}" alt="antMan">
                    <div class="nameBx">
                        <div class="name">
                            <h2>Ant Man</h2>
                            <h4>today,<span>09:45 pm</span></h4>
                        </div>
                        <div class="mess">
                            <h3>Good luck! Captain.</h3>
                            <i class="fal fa-check-double" id="clr"></i>
                        </div>
                    </div>
                </a>
            {% endfor %}


            <a href="{% url 'chatadvanced:chat' "pistonchi" %}">
                <img src="{% static 'images/blackPanther.jpg' %}" alt="antMan">
                <div class="nameBx">
                    <div class="name">
                        <h2>Black Panther</h2>
                        <h4>today,<span>12:10 pm</span></h4>
                    </div>
                    <div class="mess">
                        <h3>mission complete.</h3>
                        <i class="fal fa-check-double"></i>
                    </div>
                </div>
            </a>
            <a href="{% url 'chatadvanced:chat' "asadbek" %}">
                <img src="{% static 'images/captainAmerica.jpg' %}" alt="antMan">
                <div class="nameBx">
                    <div class="name">
                        <h2>Captain America</h2>
                        <h4>today,<span>12:10 pm</span></h4>
                    </div>
                    <div class="mess">
                        <h3>mission complete.</h3>
                        <span>2</span>
                    </div>
                </div>
            </a>
            <a href="{% url 'chatadvanced:chat' "diyorbek" %}">
                <img src="{% static 'images/doctorStrange.jpg' %}" alt="antMan">
                <div class="nameBx">
                    <div class="name">
                        <h2>Doctor Strange</h2>
                        <h4>today,<span>12:10 pm</span></h4>
                    </div>
                    <div class="mess">
                        <h3>mission complete.</h3>
                        <i class="fal fa-check-double"></i>
                    </div>
                </div>
            </a>

        </div>
    </main>
    <div class="right">
        {% block chat %}
            <div style="display: flex; align-items: center; justify-content: center; height: 100%; width: 100%">
                <h1 style="opacity: .5; ">
                    Chat tanlanmagan!
                </h1>
            </div>
        {% endblock %}
    </div>
{% endblock %}